version: '2.4'

services:
  api:
    build:
      context: ./docker/api/
    environment:
#     normal mode
      JAVA_OPTS: '-Xmx256m -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.ssl=false'
#      debug mode
#      JAVA_OPTS: '-Xmx256m -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.ssl=false -agentlib:jdwp=transport=dt_socket,address=2099,server=y,suspend=y'
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/linksdb
    ports:
      - '9090:9090'
      - '3099:1099'
      - '4099:2099'
    volumes:
      - ./api/build/libs/api.jar:/app/app.jar
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -fs http://localhost:9090/actuator/health']
  ui:
    build:
      context: ./docker/ui/
    environment:
#     normal mode
      JAVA_OPTS: '-Xmx256m -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.ssl=false'
#      debug mode
#      JAVA_OPTS: '-Xmx256m -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.ssl=false -agentlib:jdwp=transport=dt_socket,address=2099,server=y,suspend=y'
      baseApiUrl: http://api:9090
    ports:
      - '8080:8080'
      - '1099:1099'
      - '2099:2099'
    volumes:
      - ./ui/build/libs/ui.jar:/app/app.jar
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -fs http://localhost:8080/actuator/health']
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ['CMD-SHELL', '/usr/bin/mysql --user=root --password=root --execute "SHOW DATABASES;"']
